name: wren_dart
description: Dart wrappers for Wren
version: 0.2.0
repository: https://github.com/nailuj29gaming/wren-dart
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  ffigen: ^2.2.5
  pedantic: ^1.9.0
  test: ^1.14.4

ffigen:
  name: WrenBindings
  description: Bindings to Wren
  output: 'lib/src/generated_bindings.dart'
  headers:
    entry-points:
      - 'wren.h'
