name: wren_dart
description: Dart wrappers for Wren
version: 0.3.0
repository: https://github.com/Billy-Hostage/wren-dart
environment:
  sdk: '>=3.0.0'

dependencies:
  ffi: ^2.0.0
  path: ^1.7.0

dev_dependencies:
  ffigen: ^9.0.1
  test: ^1.14.4

ffigen:
  name: WrenBindings
  description: Bindings to Wren, the scripting language and its vm
  output: 'lib/src/generated_bindings.dart'
  llvm-path:
    - "C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\Llvm\\x64\\bin\\libclang.dll"
  headers:
    entry-points:
      - 'wren.h'
